"""upgrade warehouse

Revision ID: 420e6c05064e
Revises: 3fb8fd87b1d4
Create Date: 2024-08-20 15:57:11.183805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420e6c05064e'
down_revision: Union[str, None] = '3fb8fd87b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'product_count_in_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'product_count_in_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
